### PR TITLE
Iterator

### PR DESCRIPTION
**Pull request by diasjorge**
This pull request adds support so you can iterate over the outputs

### CODE REVIEW

**Comment by diasjorge** [comment]
Hi, thanks for the quick merge. How do you handle releases? Could we have a new version with this changes?
Additionally I'd like to say thanks for creating this package. I'll be sending some more changes in the upcoming weeks :)

**Comment by adonig** [comment]
Thanks for contributing! I’m currently working on something completely different, but I could come up with a new release maybe like next weekend. What changes are you working on? I also have a change I wanted to add with the next release. I wanted to make use of the “new" [CloudFormation waiters](https://github.com/boto/boto3/issues/84). They look more reliable than `Stack._wait_until_done`. Please let me know if we are working on the same thing :)

**Comment by diasjorge** [comment]
Hi, so I'd like to have more information when there are errors applying the stacks

**Comment by adonig** [comment]
Hi again! I've extended `FutureOutputs` so it inherits from `collections.Mapping`. That way we can have all those nice methods like `__contains__`, `keys`, `values`, `items` etc. without a lot of manual labour. I've also extended your test and switched from `unittest` to `pytest` because IMO it's nicer having all those fixtures and stuff. You can install the development dependencies like this: `pip install -e .[dev]` and simply run the tests with `pytest`. I've removed the `iteritems` method, because it was kind of deprecated by the `items` method by [PEP 469](http://legacy.python.org/dev/peps/pep-0469/). You can key-value-iterate the outputs like this: `for key, value in stack.outputs.items():`. If you are okay with the changes, I'm probably going to package it and make it a 0.4 release tomorrow :)

**Comment by diasjorge** [comment]
Hi,

I really like the changes. I didn't want to introduce more dependencies but I also prefer pytest. 

I tried looking at the waiters you mentioned a bit but wasn't sure how to approach it. 

By the way maybe could you set up Travis so we can have the tests running for future changes?

**Comment by adonig** [comment]
Just wanted to let you know that I've pushed [a 0.3.1 release to PyPI](https://pypi.python.org/pypi?:action=display&name=aloisius&version=0.3.1). I skipped the waiters because I had no time. I'm going to try the Travis thing probably tomorrow :)

**Pull request merged**
